# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae864c2eff058241c80781a02c925b3b985f953416e9c548767c9ad7ff7f2da967bb60c1a280892c27b037f656becb6fcbb3000a5273331070572c57f674663

test:
  secret_key_base: 892d7b8cdf2538a60ee3a450d05283f284bafe48d8bf38170fe8a38ae4629b284fed6392de054e43c6f8e08fe8cd41b431b62ba9a6de04cecb7c79e70e064999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
